// TorQ-FX downloader config

files:`:files
allcpairs:`AUDCAD`AUDCHF`AUDJPY`AUDNZD`AUDUSD`AUXAUD`BCOUSD`CADCHF`CADJPY`CHFJPY`CORUSD`COTUSD`CUUUSD`ETXEUR`EURAUD`EURCAD`EURCHF`EURCZK`EURDKK`EURGBP`EURHUF`EURJPY`EURNOK`EURNZD`EURPLN`EURSEK`EURTRY`EURUSD`FRXEUR`GBPAUD`GBPCAD`GBPCHF`GBPJPY`GBPNZD`GBPUSD`GRXEUR`HGOUSD`HKXHKD`JPXJPY`NSXUSD`NTGUSD`NZDCAD`NZDCHF`NZDJPY`NZDUSD`PDUUSD`PTUUSD`SGDJPY`SOYUSD`SPXUSD`SUGUSD`UDXUSD`UKXGBP`USDCAD`USDCHF`USDCNH`USDCZK`USDDKK`USDHKD`USDHUF`USDJPY`USDMXN`USDNOK`USDPLN`USDRUB`USDSEK`USDSGD`USDTRY`USDZAR`WHTUSD`WTIUSD`XAGUSD`XAUAUD`XAUCHF`XAUEUR`XAUGBP`XAUJPY`XAUUSD`ZARJPY
runtime:17:00:00
initialrun:0b
initialrunstart:2000.05.01
emailaddresses:("test@aquaq.co.uk";"test1@aquaq.co.uk")
emailsenabled:0b
